Repository googleapis/python-webrisk, pull requests merged in 2021-04, with the labels that each got.

#60 chore: remove tarfile
  synth.metadata
  webrisk-v1-py.tar.gz
Labels: api: webrisk, cla: yes, context: none

#61 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: api: webrisk, cla: yes

#64 chore: prevent normalization of semver versioning
  setup.py
Labels: api: webrisk, automerge, cla: yes

#69 chore(revert): revert preventing normalization
  setup.py
Labels: api: webrisk, automerge, cla: yes
