Repository googleapis/python-webrisk, pull requests merged in 2021-03, with the labels that each got.

#53 chore: delete obsolete replace in synth.py
  synth.py
Labels: api: webrisk, automerge, cla: yes

#57 chore: start tracking obsolete files
  synth.metadata
Labels: api: webrisk, cla: yes, context: full

#59 build(python): update docfx job to use new plugin
  noxfile.py
  synth.metadata
  webrisk-v1-py.tar.gz
Labels: api: webrisk, cla: yes, context: partial
